### ISSUE TITLE
怎么使用regularization

### ISSUE THREAD

**Issue by Mr-Da-Yang** [duyuanchao/adaptive-l2-regularization-pytorch#1]
首先非常感谢你的复现，我在adaptive-l2-regularization-pytorch/projects/AdatpiveL2/中找到了这个函数，但是怎么部署到主函数中进行训练，可以指导以下是哪个py文件吗？我没有找到。

**Comment by duyuanchao** [comment]
you can refer to  https://github.com/JDAI-CV/fast-reid

**Comment by duyuanchao** [comment]
close the issue
