### ISSUE TITLE
adaptive_l2_loss训练问题

### ISSUE THREAD

**Issue by TragedyN** [duyuanchao/adaptive-l2-regularization-pytorch#2]
您好，谢谢您的工作，想问一下在AdatpiveL2/meta_arch_wrapper.py文件中这部分adaptive_l2_loss(self.backbone)  # TODO 需要传入参数修改 是还没有完成吗，还有您在readme中写的训练和测试代码会公开吗，谢谢！

**Comment by duyuanchao** [comment]
you can refer to https://github.com/JDAI-CV/fast-reid for training

**Comment by duyuanchao** [comment]
close the issue
